name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: List files
        run: |
          pwd
          ls -al

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: List files
        run: |
          pwd
          ls -al

      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Murat
      
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
