name: Context testing

on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: dump
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!' ) }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        continue-on-error: true
        
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
        if: failure()

      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}',
        if: success()

      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
        if: always()

      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'

      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'