name: Github Actions Secret example

on:
  push:
    branches: [ "main" ]

jobs:
  secret-in-github-actions:
    runs-on: windows-latest
    
    # The Secret Actions Github example has three steps
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a Github Actions Secret to the logs
        run: |
          echo "The Github Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo Github Actions Secret: " 
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
